# These settings are synced to GitHub by https://probot.github.io/apps/settings/
_extends: .github

repository:
  name: fastlane-plugin-saucelabs
  description: "💥 [SauceLabs](https://docs.saucelabs.com/dev/api/index.html) plugin for [Fastlane](https://fastlane.tools/)"
  topics: fastlane, saucelabs, fastlane-plugin, android, ios
  homepage: https://github.com/cloudkats/fastlane-plugin-saucelabs
  private: false
  has_projects: false
  has_wiki: false
  is_template: false
  has_downloads: false

branches:
  - name: main
