name: release-drafter

on:
  push:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      prerelease:
        description: Is this a pre-release
        required: true
        default: true
      publish:
        description: Publish release
        required: false
        default: false
      bump:
        description: 'Bumping (#major, #minor or #patch)'
        required: false
        default: patch

jobs:
  draft-a-release:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2.3.4
        with:
          repository: 'cloudkats/fastlane-plugin-saucelabs'

      - name: check next version
        uses: anothrNick/github-tag-action@1.36.0
        id: tag
        env:
          DRY_RUN: true
          WITH_V: true
          DEFAULT_BUMP: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.bump || 'patch' }}

      - name: strip-v-from-tag
        id: tag_strip
        run: |
          TAG=${{ steps.tag.outputs.new_tag }}
          echo ::set-output name=tag_w_v::${TAG#v}

      - name: plugin-version-change
        uses: DamianReeves/write-file-action@master
        with:
          path: lib/fastlane/plugin/saucelabs/version.rb
          contents: >
            module Fastlane
              module Saucelabs
                VERSION = "${{ steps.tag_strip.outputs.tag_w_v }}"
              end
            end
          write-mode: overwrite

      - name: commit-changes
        uses: EndBug/add-and-commit@v7
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish }}
        with:
          message: 'chore: update version [skip ci]'
          add: 'lib/fastlane/plugin/saucelabs/version.rb'
          branch: main

      - name: release-draft
        uses: release-drafter/release-drafter@v5.15.0
        if: "!contains(github.event.head_commit.message, 'skip')"
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          publish: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.publish || 'false' }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.prerelease || 'true' }}
          tag: ${{ steps.tag.outputs.new_tag }}

      - name: check-version
        run: |
          echo "release it: ${{ github.event.inputs.prerelease }}"
          echo "out: ${{ steps.release.name }}"
          echo "tag: ${{ steps.release.outputs.tag_name }}"
