name: release-gem

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  RUBY_VERSION: 2.7.0

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1

      - name: setup-ruby-${{ env.RUBY_VERSION }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: build gem
        run: gem build *.gemspec
      - name: publish gem to rubygems.org
        run: gem push *.gem
        env:
          GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'

      # - run: |
      #     bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
      #     bundle exec rake install
      #     version=$(cat version)
      #     gem push pkg/fastlane-plugin-saucelabs-$version.gem -k ${{ secrets.RUBYGEMS_API_KEY }}
