name: release-gem

on:
  push:
    branches:
      - "*"
    tags:
      - v*

env:
  RUBY_VERSION: 2.7.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - run: 'echo "${{ toJson(github) }}"'

      - name: setup-ruby-${{ env.RUBY_VERSION }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}
          working-directory: ${{ env.WORKING_DIRECTORY }}

      - run: |
          bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle
          bundle exec rake install
          bundle exec rake release
