name: release-gem

on:
  workflow_dispatch:
  push:
    tags:
      - v*

env:
  RUBY_VERSION: 2.7.0

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v1

      - name: setup-ruby-${{ env.RUBY_VERSION }}
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: ${{ env.RUBY_VERSION }}

      - name: build gem
        run: gem build *.gemspec

      - name: publish gem to rubygems.org
        run: gem push *.gem
        env:
          GEM_HOST_API_KEY: '${{ secrets.RUBYGEMS_API_KEY }}'

      - name: setup github packages access
        run: |
          mkdir -p ~/.gem
          echo ":github: Bearer ${{ secrets.GITHUB_TOKEN }}" >> ~/.gem/credentials
          chmod 0600 ~/.gem/credentials

      - name: publish gem to github packages
        run: gem push --key github --host https://rubygems.pkg.github.com/${{ github.repository_owner }} *.gem
